[tool.poetry]
name = "solarpark-service"
version = "0.0.2"
description = "Solar Park"
authors = ["Our Studio <hej@ourstudio.se>"]

[tool.poetry.dependencies]
python = "^3.10"
certifi = "^2023.7.22"
cryptography = "^41.0.3"
fastapi = "^0.101.1"
fastapi-mail = "^1.4.1"
geopy = "^2.3.0"
httpx = "0.24.1"
jinja2 = "^3.1.2"
pdfkit = "^1.0.0"
psycopg2 = "2.9.7"
pydantic = "^2.2.1"
pydantic-settings = "^2.0.3"
pyjwt = "^2.8.0"
pyjwt-key-fetcher = "^0.5.0"
python-dotenv = "^1.0.0"
python-json-logger = "^2.0.7"
python-multipart = "0.0.6"
requests = "^2.31.0"
sendgrid = "^6.10.0"
setuptools = "^68.1.2"
SQLAlchemy = "2.0.20"
structlog = "23.1.0"
uvicorn = "0.23.2"

[tool.poetry.dev-dependencies]
pytest = "7.2.0"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry>=1.2.2"]
build-backend = "poetry.masonry.api"
